#!/usr/bin/env python3
"""Link CVEs to the commits that fix them, and to the revision that still has the bug.

BootBench stores CVEs and vulnerability-fixing commits in separate submodules
with nothing connecting them. The benchmark's central workflow -- take a CVE,
find its fix, check out the fix's parent to get a vulnerable tree -- therefore
has to be reconstructed by hand every time.

This builds that index once. For every CVE in ``bootloader_cve_db`` it finds
the commits in ``bootloader_vuln_commits`` that name it, and records each
commit's parent, which is the last revision that still contains the bug.

It also reports the two failure directions, because both are informative:

* **Unlinked CVEs** -- in the database with no fixing commit found. Either the
  fix predates the mined history, the project never referenced the CVE in a
  commit message, or the affected bootloader is not in the corpus.
* **Orphan references** -- CVEs named in bootloader commits but absent from the
  database. These are candidates the keyword classifier missed, and are worth
  reviewing before trusting the CVE totals.

Usage
-----
    python3 link_cves_to_commits.py --root .. \
        --output ../bootloader_vuln_commits/cve-commit-links.json \
        --markdown ../bootloader_vuln_commits/LINKS.md
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

TYPES = ("type1", "type2", "type3")


def load_cves(root: Path) -> dict[str, dict[str, Any]]:
    cves: dict[str, dict[str, Any]] = {}
    for name in TYPES:
        path = root / "bootloader_cve_db" / name / f"{name}-results.json"
        if not path.is_file():
            continue
        for cve_id, entry in json.loads(path.read_text(encoding="utf-8")).items():
            cves[cve_id] = {
                "type": name,
                "description": entry.get("description", ""),
                "vuln_type": entry.get("vuln_type", "n/a"),
                "vendor": entry.get("vendor", "n/a"),
                "published_date": entry.get("published_date", ""),
            }
    return cves


def load_fix_commits(root: Path) -> list[dict[str, Any]]:
    """Every commit that names at least one CVE, with its repository."""
    commits = []
    base = root / "bootloader_vuln_commits"
    for type_dir in sorted(p for p in base.iterdir() if p.is_dir() and p.name.startswith("type")):
        for path in sorted(type_dir.glob("*.json")):
            data = json.loads(path.read_text(encoding="utf-8"))
            for entry in data.get("CVEs", []):
                ids = entry.get("cve_ids")
                if not ids:
                    continue
                commits.append({
                    "repo": f"{type_dir.name}/{path.stem}",
                    "commit": entry["commit"],
                    # The parent is the point to check out to reproduce the bug.
                    "parent": entry.get("parent"),
                    "date": entry.get("date", ""),
                    "subject": entry["message"].split("\n", 1)[0][:120],
                    "cve_ids": ids,
                })
    return commits


def build(root: Path) -> dict[str, Any]:
    cves = load_cves(root)
    commits = load_fix_commits(root)

    by_cve: dict[str, list[dict]] = defaultdict(list)
    for commit in commits:
        for cve_id in commit["cve_ids"]:
            by_cve[cve_id].append({k: commit[k] for k in
                                   ("repo", "commit", "parent", "date", "subject")})

    links = {}
    for cve_id, meta in sorted(cves.items()):
        fixes = by_cve.get(cve_id)
        if fixes:
            links[cve_id] = {**meta, "fixes": fixes}

    unlinked = sorted(set(cves) - set(links))
    orphans = sorted(set(by_cve) - set(cves))

    return {
        "links": links,
        "unlinked": unlinked,
        "orphan_references": {c: by_cve[c] for c in orphans},
        "stats": {
            "cves_total": len(cves),
            "cves_linked": len(links),
            "cves_unlinked": len(unlinked),
            "fix_commits": len(commits),
            "orphan_references": len(orphans),
            "usable_targets": sum(1 for v in links.values()
                                  if any(f["parent"] for f in v["fixes"])),
        },
    }


def render(data: dict[str, Any]) -> str:
    s = data["stats"]
    links = data["links"]
    by_type = Counter(v["type"] for v in links.values())
    by_repo = Counter(f["repo"] for v in links.values() for f in v["fixes"])

    lines = [
        "# CVE to fix-commit links", "",
        "Which CVEs in the database have a fixing commit in the corpus, and the",
        "revision to check out to get a tree that still contains the bug.", "",
        "Generated by `tools/link_cves_to_commits.py`. Regenerate after any refresh.", "",
        "## Coverage", "",
        "| | Count |",
        "|---|------:|",
        f"| CVEs in the database | {s['cves_total']:,} |",
        f"| CVEs with a fixing commit | {s['cves_linked']:,} |",
        f"| of those, with a parent to check out | {s['usable_targets']:,} |",
        f"| CVEs with no fixing commit found | {s['cves_unlinked']:,} |",
        f"| CVE-naming commits in the corpus | {s['fix_commits']:,} |",
        f"| CVEs named in commits but absent from the database | {s['orphan_references']:,} |",
        "",
        f"Linked CVEs by bootloader type: " +
        ", ".join(f"{t} {by_type.get(t, 0)}" for t in TYPES),
        "",
        "Most CVEs have no fixing commit here. That is expected: a CVE is linked",
        "only when the fix landed in a bootloader that is in the corpus *and* the",
        "commit message names the CVE. Vendor firmware fixes, silent fixes and",
        "fixes predating the mined history all fall outside.",
        "",
        "## Where the linked fixes are", "",
        "| Repository | Linked fixes |",
        "|---|------:|",
    ]
    for repo, n in by_repo.most_common(20):
        lines.append(f"| `{repo}` | {n} |")

    lines += ["", "## Using a link", "",
              "```bash",
              "# every linked CVE, its fix, and the revision that still has the bug",
              "python3 -c \"",
              "import json; d = json.load(open('cve-commit-links.json'))",
              "e = d['links']['CVE-2023-40547']",
              "print(e['fixes'][0]['repo'], e['fixes'][0]['parent'])\"",
              "",
              "# then check out the vulnerable revision",
              "git -C oss-bootloaders/type2/shim checkout <parent>",
              "```", ""]

    orphans = data["orphan_references"]
    if orphans:
        lines += ["## Orphan references", "",
                  f"{len(orphans)} CVEs are named in bootloader commits but are not in the",
                  "database. Each is either a CVE the keyword classifier missed, or a",
                  "non-bootloader CVE referenced in passing. Worth reviewing before",
                  "quoting the CVE totals.", "",
                  "| CVE | Named in |", "|---|---|"]
        for cve_id, fixes in sorted(orphans.items())[:40]:
            lines.append(f"| {cve_id} | `{fixes[0]['repo']}` |")
        if len(orphans) > 40:
            lines.append(f"| … and {len(orphans) - 40} more | |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=here.parent,
                        help="BootBench checkout root")
    parser.add_argument("--output", type=Path,
                        help="JSON index to write (default: bootloader_vuln_commits/cve-commit-links.json)")
    parser.add_argument("--markdown", type=Path,
                        help="also write a summary table here")
    args = parser.parse_args()

    root = args.root.resolve()
    data = build(root)
    out = args.output or root / "bootloader_vuln_commits" / "cve-commit-links.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

    s = data["stats"]
    print(f"[INFO] {s['cves_linked']} of {s['cves_total']} CVEs linked to a fixing commit "
          f"({s['usable_targets']} with a checkout-able parent)")
    print(f"[INFO] {s['orphan_references']} CVEs named in commits but absent from the database")
    print(f"[INFO] index written to {out}")

    if args.markdown:
        args.markdown.write_text(render(data), encoding="utf-8")
        print(f"[INFO] summary written to {args.markdown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
