#!/usr/bin/env python3
"""Check the wiki's technical claims against the source they describe.

The prose in `wiki_content.py` is the one part of the wiki that is written
rather than generated, so it is the one part that can be wrong. Most of it
names something concrete -- a stage, a symbol, a structure, a file -- and those
names either appear in the project's own tree or they do not.

This walks every backticked identifier and every stage name in the prose,
greps the bootloader's own submodule for it, and records where it was found.
`--write` refreshes `claim_evidence.json`; the default mode re-checks it.

Identifiers that legitimately do not appear in a project's own tree -- a
cross-project reference, or a deliberate claim of absence -- must be listed
under `cross_reference` with a reason. Nothing may simply go unexplained.
"""

from __future__ import annotations

import argparse
import configparser
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
EVIDENCE = HERE / "claim_evidence.json"

sys.path.insert(0, str(HERE))
from wiki_content import BOOTLOADERS  # noqa: E402

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_.+\-]*$")
# GUIDs and other digit-initial constants are the most falsifiable claims
# in the prose, so they must not fall outside the sweep.
CONST = re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F-]{20,}$|^0x[0-9A-Fa-f]{2,}$")


def submodule_paths() -> dict[str, list[str]]:
    """Map a corpus name to its path(s). Two submodules share the name
    `bootloader`, so a name can resolve to more than one tree."""
    cp = configparser.ConfigParser()
    cp.read_string((ROOT / "oss-bootloaders" / ".gitmodules").read_text())
    out: dict[str, list[str]] = {}
    for section in cp.sections():
        path = cp.get(section, "path")
        out.setdefault(path.split("/")[-1], []).append(path)
    return out


def claimed_identifiers(name: str) -> list[str]:
    b = BOOTLOADERS[name]
    text = " ".join([b.boot_role, b.type_rationale, b.communication, b.handoff]
                    + [f"{s.name} {s.what} {s.carries}" for s in b.stages])
    toks = {t for t in re.findall(r"`([^`]+)`", text)
            if (IDENT.match(t) and len(t) > 2) or CONST.match(t)}
    for stage in b.stages:
        if IDENT.match(stage.name) and len(stage.name) > 2:
            toks.add(stage.name)
    return sorted(toks)


def find(token: str, paths: list[str]) -> str | None:
    """First file under any of `paths` containing `token`, or None."""
    for rel in paths:
        tree = ROOT / "oss-bootloaders" / rel
        if not tree.is_dir():
            continue
        try:
            r = subprocess.run(
                ["grep", "-rilF", "--exclude-dir=.git", "-m1", "--", token, str(tree)],
                timeout=180, capture_output=True, text=True)
        except subprocess.TimeoutExpired:
            continue
        if r.returncode == 0 and r.stdout.strip():
            hit = r.stdout.splitlines()[0]
            return str(Path(hit).relative_to(ROOT / "oss-bootloaders"))
    return None


def sweep() -> dict[str, dict[str, str | None]]:
    paths = submodule_paths()
    found: dict[str, dict[str, str | None]] = {}
    for name in sorted(BOOTLOADERS):
        found[name] = {tok: find(tok, paths.get(name, []))
                       for tok in claimed_identifiers(name)}
        print(f"[INFO] {name}: {sum(v is not None for v in found[name].values())}"
              f"/{len(found[name])} identifiers located", file=sys.stderr)
    return found


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true",
                    help="refresh claim_evidence.json from the current sources")
    args = ap.parse_args()

    record = json.loads(EVIDENCE.read_text()) if EVIDENCE.exists() else {}
    excused = {k: v for k, v in record.get("cross_reference", {}).items()}
    found = sweep()

    unexplained = []
    for name, toks in found.items():
        for tok, where in toks.items():
            if where is None and f"{name}:{tok}" not in excused:
                unexplained.append(f"{name}: `{tok}` not found in its source, "
                                   f"and no cross_reference entry explains why")

    if args.write:
        EVIDENCE.write_text(json.dumps(
            {"_comment": "Generated by verify_claims.py --write. Each entry is an "
                         "identifier the wiki prose names, and the file in the "
                         "project's own tree where it was found.",
             "cross_reference": excused,
             "verified": {n: {t: w for t, w in sorted(v.items()) if w}
                          for n, v in sorted(found.items())}},
            indent=1) + "\n")
        print(f"[INFO] wrote {EVIDENCE.name}")

    total = sum(len(v) for v in found.values())
    ok = sum(1 for v in found.values() for w in v.values() if w is not None)
    print(f"[INFO] {ok} of {total} claimed identifiers located in source; "
          f"{len(excused)} explained as cross-references")
    if unexplained:
        print("[FAIL] unexplained claims:")
        for u in unexplained:
            print("   ", u)
        return 1
    print("[OK] every claimed identifier is either found in source or explained")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
